### ISSUE TITLE
project

### ISSUE THREAD

**Issue by chrisc6** [ghbondar/webDevClass-Hub#29]
I have a big problem with my website. Last wednesday I had the same problem but we fixed it in class. My old website works fine colors, pictures, javascript and everything works how its supposed too. When I made the old folder everything went away last Wednesday and then you helped me fix it in class. I haven't made any changes since then and now everything is not working again. Im not sure what the problem is nor do I know how to fix it. No colors, pictures, or my menu bar work. I don't know what the problem is.

**Comment by emilyberger3** [comment]
I have fixed all the problems within my code but when I go to validate the code, it comes up with a bunch of random errors that are incorrect.

**Comment by Jazour11** [comment]
When I first created my new web-page I created a folder called resume, to store my resume, when I go to delete that folder to put my resume into my separate html folder it will not allow me to do so. It also will not allow me to remove the resume file from that folder.

**Comment by emilyberger3** [comment]
also you told us to clean up our text and take out comments because professionals wouldn't have those in their text. I deleted all of mine but then was reading the guidelines and it says to have comments.

**Comment by ghbondar** [comment]
@chrisc6  @emilyberger3 The project version of your index.html file should be the only file sitting in your public_html folder. From there, you needed to update the links to your files in the other folders. 
Instead of using `filename` you should use `folder/filename`.
For example, to link to Chris' css, which should be sitting in a css-folder:
`<link rel="stylesheet" type="text/css" href="css/BGcolor.css" />`

@emilyberger3 : As I explained in the rubric-comments of your homeworks, and in class, **your** ssi is adding a whole bunch of redundant tags (html, head, body, etc): the ssi should **only** be those elements that you want to include, it should not be a well-formed html document. So, all of those errors caught by the validator are meaningful, but easy to fix. The only necessary comments in your code are those explaining, for example, what each section of code is for in your html, css, and javascript, and to indicate in your html where the ssi was inserted.

@Jazour11  Can you copy the file into your html folder without deleting it?

**Comment by Jazour11** [comment]
When I try to do that it looks like it is going to transfer, but it never stays in the html folder.

**Comment by ghbondar** [comment]
@Jazour11 You can try uploading the file straight from your computer?

**Comment by Jazour11** [comment]
Ya I have tried to upload it to html from my computer it looks like it going to transfer, and it does not transfer. It seems like it is not allowing it because it is already in the resume folder. That is why I tried to delete is folder, and the contents in it, but it just says unsuccessful. I currently have the ssi, and the other pages that link to my resume linked to resume folder, and it does work, but I can not put the resume in the html folder for some reason.
